### PR TITLE
[Merge after knorth55/jsk_common#3] [jsk_fetch_startup] Use image hz convert for recording kitchen demo

### PR DESCRIPTION
**Pull request by tkmtnt7000**
Moved from #195
Merge after knorth55/jsk_common#3

This pull request addresses the issue of the incorrect correspondence between audio and video in the recording video of kitchen demo by keeping the topic hz stable.

### CODE REVIEW

**Comment by knorth55** [comment]
I rebased `fetch15`, so can you rebase the branch?

**Comment by knorth55** [comment]
you also need to change `jsk_fetch.rosinstall.melodic` to use `knorth55/jsk_common@fetch15`.

**Comment by tkmtnt7000** [comment]
Thank you for your information.
I'll resolve conflicts.
And I send PR of changing jsk_fetch.rosintall.melodic

**Comment by knorth55** [comment]
> And I send PR of changing jsk_fetch.rosintall.melodic

You can include this change to this PR.

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
