### PR TITLE
[jsk_fetch_startup] change global_planner

### PR DESCRIPTION
**Pull request by sktometometo**
changed base_global_planner from Navfn to global_planner/GlobalPlanner

### CODE REVIEW

**Comment by knorth55** [comment]
why do you need to change the planner?

**Comment by sktometometo** [comment]
I think global_planner seems to include all features of Navfn and it also can be configured with dynamic_reconfigure. So I think global_planner is more flexible and useful for our uses.

**Comment by knorth55** [comment]
did you check if it works? 
and also did you check all parameters same as navfn are correctly set?
https://github.com/fetchrobotics/fetch_ros/blob/melodic-devel/fetch_navigation/config/move_base.yaml#L11-L21

**Comment by sktometometo** [comment]
Now global_planner with these paremeters works same as current Navfn planner.
I confirmed that this can run with a real machine, but this seems not to be enough for the kitchen demo to work well yet....

**Pull request closed without merging**
