### PR TITLE
[jsk_fetch_startup] seeing more place in kitchen demo

### PR DESCRIPTION
**Pull request by mqcmd196**

### CODE REVIEW

**Comment by mqcmd196** [comment]
I've added 6 places to check everyday kitchen demo. I confirmed it works well

**Comment by knorth55** [comment]
i want to merge this, and it seems ok to me.
can you review this pr? @708yamaguchi

**Review by 708yamaguchi — APPROVED** [review]
@knorth55 
The demo is working fine, so I think this PR can be merged.

@mqcmd196 
It would be helpful if you comment email title, by which you verify this PR.
e.g. `Fetch kitchen patrol demo: 2022/08/12 (20:03:51)`
It makes it easier for later fetch users to check how this PR works. 

I have one question.
Is the `/photo_taken` topic a must?

In my understanding, you want to save important images by rosbag, but we already send important images by the following features.
email_topic.py
https://github.com/knorth55/jsk_robot/blob/f4a056bd2e02adee6a8af1284c447837f67d8fe1/jsk_fetch_robot/jsk_fetch_startup/euslisp/navigation-utils.l#L485
gdrive
https://github.com/knorth55/jsk_robot/blob/f4a056bd2e02adee6a8af1284c447837f67d8fe1/jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.app#L112

In this way, various features (e.g. email_topic.py, gdrive uploader, photo_taken) correct important images in various places (e.g. /tmp, gmail, google drive).
It would be better to unify them (in the future, not in this PR)

**Comment by mqcmd196** [comment]
Thank you for your reviewing and merging!

> I have one question.
> Is the /photo_taken topic a must?

There are already many functions for storing photos, but I wanted to include the robot's position and camera information in the rosbag form, where tf, camera_info, etc. are stored. It may be possible to merge this function with the current photo storage function in some way.

**Pull request merged**
