### PR TITLE
[jsk_robot_startup] Replace audio/video recorder with rosbag converter in go-to-kitchen demo

### PR DESCRIPTION
**Pull request by 708yamaguchi**
With this PR, we can generate video files from rosbag after the go-to-kitchen demo.
I this case, we do not have to generate the video files while the demo is running.
This can reduce CPU usage during the demo compared to audio_video_recorder.

Related to https://github.com/knorth55/app_manager/pull/2, https://github.com/knorth55/app_manager_utils/pull/54 and https://github.com/knorth55/jsk_common/pull/11

I currently uses 708yamaguchi branches in `jsk_fetch.rosinstall.melodic`
If the above PRs work well, I will replace the 708yamaguchi branches with the knorth55 branches.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
@iory 
Could you review this?

**Comment by tkmtnt7000** [comment]
https://github.com/knorth55/jsk_robot/blob/9859ae1ec24e271881c80abc16de82566ab22043/jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml#L10-L19

If we use something like rosbag_converter instead of audio_video_recorder, we also should remove or comment out this node to suppress CPU load.  `/head_camera/rgb/image_rect_color/hz_converted` will not use after merging this PR.

**Review by tkmtnt7000 — COMMENTED** [review]
https://github.com/knorth55/jsk_robot/blob/9859ae1ec24e271881c80abc16de82566ab22043/jsk_fetch_robot/jsk_fetch_startup/apps/go_to_kitchen/go_to_kitchen.xml#L10-L19

If we use rosbag_converter instead of audio_video_recorder, we also should remove or comment out this node to suppress CPU load.  `/head_camera/rgb/image_rect_color/hz_converted` will not use after merging this PR.

**Comment by 708yamaguchi** [comment]
The latest kitchen demo with this PR is `Fetch kitchen patrol demo: 2022/06/02 (19:14:34)`
All files are uploaded successfully.

**Comment by 708yamaguchi** [comment]
@tkmtnt7000 

Thank you for your advice!
I removed `topic_hz_converter.py`

**Review by iory — APPROVED** [review]

**Review by tkmtnt7000 — APPROVED** [review]

**Pull request merged**
