### PR TITLE
[jsk_fetch_startup] rename update_workspace.sh to update_workspace_ma…

### PR DESCRIPTION
**Pull request by sktometometo**
…in.sh and call it from update_workspace.sh

If there are some changes on update_workspace.sh, it will be changed during execution of update_workspace.sh.
This sometimes leads to unexpected behavior. This PR fix it.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Yes.
Currently, the change in `update_workspace.sh` is reverted when `update_workspace.sh` itself is executed.

Because of this line.
```
wstool foreach -t $WORKSPACE/src --git 'git stash'
```

I think your idea is good, but one thing.
How about making `update_workspace_main.sh` non-executable by wrapping all of `update_workspace_main.sh` by main function and calling the main function from `update_workspace.sh`?

I think this approach prevents mistakes of executing `update_workspace.sh`.

**Comment by 708yamaguchi** [comment]
How about adding

cp /tmp/update_workspace.sh $(rospack find jsk_fetch_startup)/scripts/update_workspace_main.sh

at the last of update_workspace.sh

**Comment by sktometometo** [comment]
I mean if there are some unfetched commits with changes of update_workspace.sh, update_workspace.sh will change during update.
Stashing of unstaged change is intended behavior.

**Comment by 708yamaguchi** [comment]
> I mean if there are some unfetched commits with changes of update_workspace.sh, update_workspace.sh will change during update.

OK, I see.
Even in that case, what about the following changes?

- making update_workspace_main.sh non-executable by wrapping all of update_workspace_main.sh by main function and calling the main function from update_workspace.sh
- `cp /tmp/update_workspace.sh $(rospack find jsk_fetch_startup)/scripts/update_workspace_main.sh` at the last of update_workspace.sh

**Comment by sktometometo** [comment]
current `update_workspace.sh` makes workspace configuration up to date and remove/stash all unstage chagnges. Secont option does not match this.

First option seems not necessary. what are pros. and cons. of it?

**Comment by 708yamaguchi** [comment]
OK, I see.

As I said,
pros
> I think this approach prevents mistakes of executing update_workspace.sh.

**Review by 708yamaguchi — APPROVED** [review]

**Pull request merged**
