### PR TITLE
[fetch] update rosbag record and play

### PR DESCRIPTION
**Pull request by sktometometo**
- add rosbag_record.launch and rosbag_play.launch to jsk_fetch_startup
  - these launch files enables to record and play rosbag files including latched topic like statc_tf
- add latched_topic_republihser.py
  - this script enables to republishe latched topic like tf_static from a rosbag file.
- changed rosbag procedure in daily kitchen demo to rosbag_record.launch

### CODE REVIEW

**Comment by knorth55** [comment]
@sktometometo do we need `rosout`?

**Comment by sktometometo** [comment]
/rosout includes rosconsole outputs. I think those are useful in debuging.

For image topics, yes, it is better to record compressed images


2020年4月29日(水) 22:13 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
now I tried with this topic lists, but rosbag is too big to upload.
did you try it on real robot?

**Comment by sktometometo** [comment]
No i didnt

2020年4月29日(水) 22:27 Shingo Kitagawa <notifications@github.com>:

**Comment by sktometometo** [comment]
what kinds of errors are there with current rosbag configuration?

Is there filesize limitation to google drive upload script? or Is the
filesize just too large?

2020年4月29日(水) 22:31 Koki Shinjo <sktometometo@gmail.com>:

**Comment by sktometometo** [comment]
I am sorry for forgetting to add WIP tag to the title.

2020年4月29日(水) 22:34 Koki Shinjo <notifications@github.com>:

**Comment by knorth55** [comment]
I reverted once, so can you open a PR again?

**Comment by knorth55** [comment]
@sktometometo 256MB took almost 2 minutes to upload. it is very slow to upload a big file. I don't know why...

**Pull request merged**
