### PR TITLE
Suppress warnings when using :fast in :angle-vector

### PR DESCRIPTION
**Pull request by Affonso-Gui**
From `:angle-vector-motion-plan` description:

```lisp
- total-time : time to execute the whole motion in [msec]
   if designated total-time is shorter than the planned time, use the planned time
   if not specified, use the planned time
   if :fast is specified, use 'scale' times of the planned time
```

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Add `:use-base` keyarg
```lisp
(send *fetch* :inverse-kinematics (make-coords :pos #f(1200 0 786)) :use-base t :base-range (list :min #f(0 0 0) :max #f(100 0 0)))
```

**Comment by knorth55** [comment]
i merged this pr, but fetch is not omni wheel robot.
if you solve ik with base, it would not be same as pr2 because fetch is non-holonomic.

**Comment by Affonso-Gui** [comment]
Yes, I do believe that the main use case will be to limit the base-range to the x axis, as in the example above.

(Maybe we should set the default value to something alike?

**Comment by knorth55** [comment]
probably it is better to limit y-axis movement.

**Pull request merged**
