### PR TITLE
[fetcheus] update args

### PR DESCRIPTION
**Pull request by sktometometo**
This PR enables to give other key args to constructor of `fetch-interface`, and with this feature, we can give arguments for superclass like `:move_base_action_name`.

For example, if there are another move_base node with different configuration than ordinal one and it has an action interface whose name is `/move_base_no_recovery/`. We can specify the name when constructing robot interface by

```bash
(setq *ri* (instance fetch-interface :init :move-base-action-name "move_base_no_recovery"))
```

### CODE REVIEW

**Comment by knorth55** [comment]
&rest args position is quite important, but why did you change the position?

**Comment by sktometometo** [comment]
That seems necessary for args to be given extra keyword args.
Minimal example is below.

```lisp
(defun test01 (&key (arg01 t) &rest args)
  (format t "test01")
  (format t "arg01: ~A~%" arg01)
  (format t "args: ~A~%" args)
  )

(defun test02 (&key (arg01 t) &rest args &allow-other-keys)
  (format t "test02")
  (format t "arg01: ~A~%" arg01)
  (format t "args: ~A~%" args)
  )

(defun test03 (&rest args &key (arg01 t) &allow-other-keys)
  (format t "test03")
  (format t "arg01: ~A~%" arg01)
  (format t "args: ~A~%" args)
  )


;(test01 :hoge "fuga") ; this line causes an error
(test02 :hoge "fuga")
(test03 :hoge "fuga")
```

The output of this script is

```
test02arg01: t
args: nil
test03arg01: t
args: (:hoge fuga)
```

**Comment by knorth55** [comment]
current behavior is same as test03, and you change it to test02 in this PR.
why?

**Comment by sktometometo** [comment]
Current is test01, I have changed this to test03.

**Comment by knorth55** [comment]
you mean allow other keys, right.
so it is better to change from test01 to test02 for `&rest args`.
Why do you need to change it to test03?
I don't see any reason to change the behavior.

**Comment by sktometometo** [comment]
Because test02 cannot pass other keyword args to `args` like example.

**Comment by knorth55** [comment]
you think it is better, but it is just your opinion.
and i think is is not always better because parsing might be more difficult.
you dont use the `&rest args`, so please leave it in the original position.

**Comment by sktometometo** [comment]
So this PR doesn't work for the original purpose like test02 example. If this PR is not approved, I will close it.

**Comment by knorth55** [comment]
I checked, and you are right.
it was my misunderstanding, sorry for that.

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
