### PR TITLE
[jsk_fetch_startup] Add audible warning

### PR DESCRIPTION
**Pull request by iory**

### CODE REVIEW

**Comment by iory** [comment]
We (@iory @708yamaguchi @tkmtnt7000) confirmed this works.

**Review by tkmtnt7000 — APPROVED** [review]

**Comment by 708yamaguchi** [comment]
I think `audible_warning` works very well, thank you so much!

But before mering, we need to remove diagnostics feature from `jsk_fetch_startup/warning.py` like below.
https://github.com/knorth55/jsk_robot/pull/223

**Comment by iory** [comment]
Thank you!

> But before mering, we need to remove diagnostics feature from jsk_fetch_startup/warning.py like below.

I cherry-picked the commit.

**Comment by 708yamaguchi** [comment]
Checked with @tkmtnt7000

**Pull request merged**
