### PR TITLE
[jsk_fetch_startup] Do not stop auto-dock to cause timeout and shutdown in go-to-kitchen

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Today fetch is stucked during AUTO-DOCK after INSPECT-TRASHCAN.

```
Following smach is reported.
 - At 2021-12-25T09:00:22, Active states is REPORT-START-GO-TO-KITCHEN.
 - At 2021-12-25T09:00:25, Active states is GET-LIGHT-ON.
 - At 2021-12-25T09:00:26, Active states is ROOM-LIGHT-ON.
 - At 2021-12-25T09:00:32, Active states is MOVE-TO-SINK-FRONT.
 - At 2021-12-25T09:01:07, Active states is INSPECT-KITCHEN.
 - At 2021-12-25T09:01:26, Active states is MOVE-TO-TRASHCAN-FRONT.
 - At 2021-12-25T09:01:35, Active states is INSPECT-TRASHCAN.
```

From a battery protection point of view, we want fetch to shutdown in this situation.

So, I increased the number of trials for auto-dock and made it timeout if AUTO-DOCK stucked.
When go-to-kitchen times out, fetch will shut down.

@tkmtnt7000

If you have any good idea, please teach me.

### CODE REVIEW

**Comment by tkmtnt7000** [comment]
Sorry for late response.
Basically, I agree with the method of increasing the number of trials for auto-dock and aiming for timeout.

By the way, I think today's kitchen-demo failed, due to the fact that the process of `kitchen-demo` has been stucked in the `INSPECT-TRASHCAN` state. It is because the process for no recognition result was not well written.
I fix it in https://github.com/knorth55/jsk_robot/pull/171

**Comment by knorth55** [comment]
I don't agree this PR, because go-to-kitchen report will not send to us until 999 trial ends.
Otherwise, it is better to have some kind of rescue app,
which recognize that Fetch is stuck at some part and ask if Fetch should go back to dock or not by e-mail.
It can be done by monitoring the battery percentage and follow joint trajectory or cmd_vel command.

**Comment by 708yamaguchi** [comment]
> it is better to have some kind of rescue app,
> which recognize that Fetch is stuck at some part and ask if Fetch should go back to dock or not by e-mail.

Yes, that's correct.
We should have rescue app.

I am sorry for confusing, but I misunderstood that the reason for the go-to-kitchen failure was the failure of auto-dock.
So, my concern when I submitted this pull request was the navigation stuck.

I was hoping that fetch would shut down for battery protection when fetch's move_base got stuck during go-to-kitchen.

Currently, I think that publishing a /shutdown topic in both cases of `exit_code==1` and `timeout == True` will ensure that fetch shutdown when navigation is stuck.

**Comment by 708yamaguchi** [comment]
I add condition to publish `/shutdown`
```
cond:
  - timeout
  - failure
```

`timeout` is useful when robot stuck by navigation problem. (e.g. robot gets too close to the wall and cannot move anymore) 
`failure` is useful when robot stuck by program problem. (e.g. go-to-kitchen main roseus program stops by program bugs.)

**Pull request merged**
