### PR TITLE
[jsk_fetch_startup] Remove pointcloud from filters to disable publishing pointcloud

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I want to have option to disable pointcloud to reduce CPU usage. (200% is used on average)
However, I cannot disable pointcloud even when I set `enable_pointcloud` to false.
This is because `pointcloud` is set to `filters` rosparam by default.
c.f.
https://github.com/IntelRealSense/realsense-ros/blob/579a465a7dece96c514d1258ef0960e6de461422/realsense2_camera/src/base_realsense_node.cpp#L738-L739

@sktometometo 
Can you explain why this filter is needed?
In addition, please add documentation or comment about why you need JSK version realsense node, why you use standalone and why you need to change many params?
c.f.
https://github.com/knorth55/jsk_robot/pull/82

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
I think pointcloud fps generated by realsense node is higher than we need.

So another purpose of this PR is to generate pointcloud with lower CPU usage by the following steps.
- publish only rgb and depth images from realsense node
- throttle each topic (e.g. 30Hz to 5Hz)
- create pointcloud from throttled rgb images and depth images (For registration process, can I use nodelet manager? or I need to use standalone?)

c.f.
https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_rgbd.launch

**Comment by sktometometo** [comment]
Filter configuration is copied from original source. So modify it if needed. Cocept of the option sounds good.

**Comment by 708yamaguchi** [comment]
Which file is the original source??

also I want to know why standalone is needed.

**Comment by sktometometo** [comment]
I don't fully remember but may be https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_d435_camera_with_model.launch.

**Comment by sktometometo** [comment]
As far as I remember, I had changed base nodelet.launch.xml in order to

- give `respawn` option. The xml does not have it in that time.
- make `standalone` to default for debugging. This is not necessary now.

**Review by sktometometo — APPROVED** [review]

**Comment by 708yamaguchi** [comment]
ok, I see.

**Pull request merged**
