### PR TITLE
[jsk_fetch_startup] Add trashcan occupancy recognition to go-to-kitchen demo

### PR DESCRIPTION
**Pull request by tkmtnt7000**
This PR updates go-to-kitchen demo to notify trashcan occupancy.
I haven't been able to get the correct values for trashcan occupancy yet...
Please let me know if I should separate PR for garbage volume recognition and kitchen-demo.

cc: @mqcmd196
Thank you very much for making trashbin occupancy recognition!

### CODE REVIEW

**Review by 708yamaguchi — CHANGES_REQUESTED** [review]
Great work!

However, I think `container_occupancy_detector` should be moved to `jsk_pcl_ros`.

`container_occupancy_detector`'s feature seems not only for fetch but also for many other robots.

> I haven't been able to get the correct values for trashcan occupancy yet...

To prevent problems in real-world environments, `container_occupancy_detector` should
- be moved to `jsk_pcl_ros`
- add sample launch with rosbag (You can use go to kitchen app rosbag)
- add test

If you finish these tasks, please merge your commits into sktometometo/develop/fetch branch.
By doing this, your commits can be managed by wstool.

https://github.com/knorth55/jsk_robot/blob/05257fc1e38b4d1fa4ce45d647e8a1b3a46b4c69/jsk_fetch_robot/jsk_fetch.rosinstall.melodic#L51-L54

**Comment by 708yamaguchi** [comment]
@mqcmd196

**Comment by mqcmd196** [comment]
I understand the importance 

> However, I think container_occupancy_detector should be moved to jsk_pcl_ros.
> 
> container_occupancy_detector's feature seems not only for fetch but also for many other robots.
> 
> I haven't been able to get the correct values for trashcan occupancy yet...
> 
> To prevent problems in real-world environments, container_occupancy_detector should
> 
> be moved to jsk_pcl_ros
> add sample launch with rosbag (You can use go to kitchen app rosbag)
> add test
> If you finish these tasks, please merge your commits into sktometometo/develop/fetch branch.
> By doing this, your commits can be managed by wstool.
> 

however there are so many problems or things should be considered and I might have no enough time to do those things until this year or Tsukamoto-kun's thesis. So my idea is merge those features into knorth55/fetch15 at first, then I make some improvement with kitchen-demo, at last I make PR to jsk_pcl_ros. I promise send PR jsk_prl_ros finally.

**Comment by mqcmd196** [comment]
@tkmtnt7000 

> I haven't been able to get the correct values for trashcan occupancy yet...

I'll check it. `-40....` value is quite strange, maybe detecting trashbin not works well.

**Comment by 708yamaguchi** [comment]
> however there are so many problems or things should be considered and I might have no enough time to do those things until this year or Tsukamoto-kun's thesis. So my idea is merge those features into knorth55/fetch15 at first, then I make some improvement with kitchen-demo, at last I make PR to jsk_pcl_ros.

OK, I see.

I will revert these commits if you make PR to jsk_pcl_ros.

**Pull request merged**
